services:
  db:
    image: mariadb:11.8.2-noble
    container_name: db
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    volumes:
      - ./db/live:/var/lib/mysql
    restart: always
    expose:
      - 3306
  caddy:
    image: caddy:2.10.0
    container_name: caddy
    environment:
      SERVER_NAME:
      TLS_AUTO_EMAIL:
      TLS_MODE:
      WP_DOMAIN:
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/tls_auto:/etc/tls_auto
      - ./caddy/tls_selfsigned:/etc/tls_selfsigned
      - ./wordpress:/var/www/html
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 64M
  wordpress:
    build:
      context: .
      dockerfile: dockerfiles/wordpress.dockerfile
    container_name: wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WP_HOME:
      WP_SITEURL:
      UPLOAD_MAX_FILESIZE: 64M
    expose:
      - 9000
    volumes:
      - ./wordpress:/var/www/html
    restart: always
