services:
  db:
    image: mariadb:10.6.4-focal
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - wordpress
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always
    expose:
      - 3306
      - 33060
  caddy:
    image: caddy:2.7-alpine
    env_file:
      - ./caddy/.env
    restart: always
    networks:
      - wordpress
    depends_on:
      - wordpress
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/tls_auto:/etc/tls_auto
      - ./caddy/tls_selfsigned:/etc/tls_selfsigned
      - ./wordpress:/var/www/html
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
  wordpress:
    image: wordpress:6-fpm
    networks:
      - wordpress
    depends_on:
      - db
    environment:
      PHP_MEMORY_LIMIT: 2048M
      PHP_ENABLE_XDEBUG: false
      DEBUG: false
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      UPLOAD_MAX_FILESIZE: 64M
    expose:
      - 9000
    volumes:
      - ./wordpress:/var/www/html
    restart: always

networks:
  wordpress:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
