services:
  db:
    image: mariadb:10.6.4-focal
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    expose:
      - 3306
      - 33060
  nginx:
    image: nginx:latest
    restart: unless-stopped
    environment:
      SERVER_NAME:
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/certificate.crt:/etc/ssl/certificate.crt
      - ./nginx/private.key:/etc/ssl/private.key
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/redirect.conf:/etc/nginx/conf.d/redirect.conf
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER:
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_NAME:
    expose:
      - 80
    volumes:
      - wp_data:/var/www/html
    restart: always

volumes:
  db_data:
  nginx_secrets:
  wp_data:
