services:
  db:
    image: mariadb:10.6.4-focal
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - wordpress
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always
    expose:
      - 3306
      - 33060
  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - wordpress
    networks:
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/etc/ssl:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
  wordpress:
    image: wordpress:6-fpm
    networks:
      - wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    expose:
      - 9000
    volumes:
      - ./wordpress:/var/www/html
    restart: always

networks:
  wordpress:
    driver: bridge
