name: EB Deployment
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:
env:
  GH_ACTIONS_ROLE: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GitHubActionsRole

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ env.GH_ACTIONS_ROLE }}
      - name: Prepare deployment package
        run: ./scripts/deployment-prep.sh
        env:
          TLS_AUTO_EMAIL: ${{ vars.TLS_AUTO_EMAIL }}
          SERVER_NAME: ${{ vars.SERVER_NAME }}
      - name: Deploy
        uses: tmshkr/blue-green-beanstalk@v5
        with:
          app_name: "wordpress"
          blue_env: ${{ vars.BLUE_ENV }}
          deploy: true
          green_env: ${{ vars.GREEN_ENV }}
          option_settings: option-settings.json
          platform_branch_name: "Docker running on 64bit Amazon Linux 2023"
          production_cname: ${{ vars.PRODUCTION_CNAME }}
          source_bundle: bundle.zip
          staging_cname: ${{ vars.STAGING_CNAME }}
          terminate_unhealthy_environment: true
          version_label: ${{ github.ref_name }}.${{ github.sha }}
