name: EB Deployment
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:
env:
  GH_ACTIONS_ROLE: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GitHubActionsRole

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ env.GH_ACTIONS_ROLE }}
      - name: Prepare deployment package
        run: ./scripts/deployment-prep.sh
        env:
          HTTPS_CERTIFICATE: ${{ vars.HTTPS_CERTIFICATE }}
          HTTPS_PRIVATE_KEY: ${{ secrets.HTTPS_PRIVATE_KEY }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
          SERVER_NAME: ${{ vars.SERVER_NAME }}
      - name: Deploy
        uses: tmshkr/blue-green-beanstalk@v5
        with:
          app_name: "wordpress"
          deploy: true
          option_settings: option-settings.json
          platform_branch_name: "Docker running on 64bit Amazon Linux 2023"
          single_env: ${{ vars.SINGLE_ENV }}
          single_env_cname: ${{ vars.SINGLE_ENV_CNAME}}
          source_bundle: bundle.zip
          version_label: ${{ github.ref_name }}.${{ github.sha }}
